[package]
name = "rustmole"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustmole"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auxtools = "0.1.0"
